require("core.plugin_config.BCE.minimap")
require("core.plugin_config.BCE.neoscroll")
require("core.plugin_config.BCE.ufo")
require("core.plugin_config.BCE.indent_blankline")
require("core.plugin_config.BCE.wilder")
require("core.plugin_config.BCE.neozoom")
require("core.plugin_config.BCE.swenv")
require("core.plugin_config.BCE.window")
