require("core.plugin_config.Interface.feline")
require("core.plugin_config.Interface.colorscheme")
require("core.plugin_config.Interface.alpha")
require("core.plugin_config.Interface.scrollbar")
require("core.plugin_config.Interface.zone")
